---
- name: Create a VM in OpenShift Virtualization
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: Create a CentOS 10 VM in OpenShift
      redhat.openshift.k8s:
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: centos10
            namespace: dvasquez46-dev
            labels:
              instancetype.kubevirt.io/default-instancetype: u1.medium
              instancetype.kubevirt.io/default-instancetype-kind: VirtualMachineClusterInstancetype
              instancetype.kubevirt.io/default-preference: centos.stream10
              instancetype.kubevirt.io/default-preference-kind: VirtualMachineClusterPreference
          spec:
            runStrategy: Manual
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: centos10
                spec:
                  sourceRef:
                    kind: DataSource
                    name: centos10-bootable
                    namespace: dvasquez46-dev
                  storage:
                    resources:
                      requests:
                        storage: 30Gi
                    storageClassName: gp3      
              spec:
                architecture: amd64
                domain:
                  devices: 
                    disks:
                      - bootOrder: 1
                        bus: virtio
                        name: rootdisk
                    interfaces:
                      - macAddress: '02:11:4d:8c:ad:eb'
                        masquerade: {}
                        name: default
                    networkInterfaceMultiqueue: true
                    rng: {}
                  features:
                    acpi: {}
                  firmware:
                    bootloader:
                      bios: {}
                  machine:
                    type: pc-q35-rhel9.2.0
                  memory:
                    guest: 4Gi
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                tolerations:
                  - effect: NoSchedule
                    key: sandbox-cnv
                    operator: Exists
                volumes:
                  - dataVolume:
                      name: centos10
                    name: rootdisk
                  - cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        users:
                          - name: cloud-user
                            sudo: ['ALL=(ALL) NOPASSWD: ALL']
                            groups: wheel
                            shell: /bin/bash
                            ssh_authorized_keys:
                              - "{{ ssh_public_key }}"
                            passwd: "{{ vm_password }}"
                            lock_passwd: false
                        chpasswd:
                          list: |
                            cloud-user:{{ vm_password }}
                          expire: False
                        ssh_authorized_keys:
                          - "{{ ssh_public_key }}"
                    name: cloudinitdisk

    - name: Wait for system to become reachable over
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 180
