---
- name: Install Apache and PostgreSQL
  hosts: all
  become: true  # This allows the tasks to run with sudo privileges
  gather_facts: false
  tasks:
    - name: Install Apache2 package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Ensure Apache2 service is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Install PostgreSQL package
      ansible.builtin.dnf:
        name: 
          - postgresql-server
          - postgresql
        state: present

    - name: Ensure PostgreSQL service is running and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
