---
- name: Patch CentOS Stream 9 Virtual Machine
  hosts: all
  become: true  # Escalate privileges to root (sudo) for system updates

  tasks:
    - name: Ensure all installed packages are updated to the latest available version
      ansible.builtin.dnf:
        name: '*'
        state: latest
        disable_excludes: all # Important: temporarily disable any package exclusion rules
        nobest: false         # Allow the solver to use the next-best solution if a package is not installable
        bugfix: true          # Limit the upgrade process to only packages tagged as bugfixes
        security: true        # Limit the upgrade process to only packages tagged as security relevant
      register: dnf_update_status

    - name: Reboot the system if a reboot is required after kernel or critical library updates
      ansible.builtin.reboot:
        reboot_timeout: 15   # Wait up to 10 minutes for the host to come back
        msg: "Rebooting {{ inventory_hostname }} to apply updates"
      when: dnf_update_status.changed_packages is defined and dnf_update_status.changed_packages | length > 0 and ansible_kernel is defined and ansible_kernel not in (dnf_update_status.results | selectattr('name', 'equalto', 'kernel-core') | map(attribute='version') | list | default([]))
      # Note: The 'when' condition above is a common heuristic, but for true accuracy,
      # use 'needs-restarting' utility checks if available on the system.
      # Example: shell: needs-restarting -r
      # register: reboot_required_check
      # changed_when: reboot_required_check.rc == 1
      # when: reboot_required_check.rc == 1
