---
- name: Install Apache and PostgreSQL
  hosts: all
  become: true  # This allows the tasks to run with sudo privileges
  gather_facts: false
  tasks:
    - name: Install Apache2 package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Ensure Apache2 service is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Install PostgreSQL package
      ansible.builtin.dnf:
        name: 
          - postgresql-server
          - postgresql
        state: present

    
    - name: Initialize the PostgreSQL database cluster (if not already initialized)
      ansible.builtin.shell: |
        /usr/bin/postgresql-setup --initdb
      args:
        creates: /var/lib/pgsql/data/postgresql.conf # Check if config file exists as an idempotency check
    
    - name: Start and enable PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
