apiVersion: kubevirt.io/v1
kind: VirtualMachine    
namespace: bgperm2-dev    
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: rhel85-devops-rootdisk
      spec:
        source:
          pvc:
            name: rhel8.5-devtools
            namespace: bgperm2-dev
        storage:
          resources:
            requests:
              storage: '21474836480'
  runStrategy: Manual
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: medium
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: rhel85-devops
        kubevirt.io/size: medium
        network.kubevirt.io/headlessService: headless
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - macAddress: '02:0d:82:1e:c9:a9'
              masquerade: {}
              model: virtio
              name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        firmware:
          serial: b2a08d20-20e4-4e4c-8ef4-3a5c22d887b9
          uuid: 107575df-40b2-4f0b-9c1b-4f7980353fd1
        machine:
          type: pc-q35-rhel8.4.0
        memory:
          guest: 4Gi
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi
      networks:
        - name: nic-0
          pod: {}
      terminationGracePeriodSeconds: 180
      evictionStrategy: LiveMigrate
      hostname: rhel85-devops
      architecture: amd64
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: tst
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              ssh_authorized_keys:
              - |
                ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWLVjB2r2pRquMPtmI/8brPq9vwc8/PJzih1/Alnbkmhv60W0EuB5adWPktX8MHsKZnaClNGrYqj18P3beD6j66RmiJkuppl0TACDb6PqfuN/E0SSbuHw8xPZLp50XKj71AITW34h9JeoX8NDVVS0d1Y3+ySXO4ITAhxWAIROCafV8CQvJEPy72/IcdLj21PVznLxb2uR82LrI06acHM+0psIf98ZqTi4u2to0P4XIYLbWZdkjS2o4dim/9YV11GrR09YfnTNPhjhtOt+e/s5ZbvE/KahFriKuwXUaII7x0NvcMSmj7dgGu3HxLNe1mZrdmTQNmfZ6UcvT+AniCShXOdHRckeK6oLvkdx1J0qUA0a0Ze0VkKSa4f1uC+I5Svs3jqFqmy2Uu8REVaajAOyyLj8Y2wacZwdlaINwPM1u5ewFezhIp1L+xzGiMEZYkGBywmldoJyTa/mBTWxt4pBDqitiGrWPjckFNBGk14ebG7AwFh5KiG0impvZxPkbMFE= sandbox@cnv
          name: cloudinitdisk
        - dataVolume:
            name: rhel85-devops-rootdisk
          name: rootdisk
      tolerations:
        - effect: NoSchedule
          key: sandbox-cnv
          operator: Exists
