---
- name: Patch CentOS VM to latest
  hosts: all # Replace with your inventory group for CentOS VMs
  become: yes # Run tasks with sudo privileges

  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest
        update_cache: yes # Update yum cache before checking for updates
      register: yum_update_result

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot the server if required
      ansible.builtin.reboot:
         msg: System is going down for reboot. Please logoff now!
        reboot_timeout: 20 # Wait up to 10 minutes for the reboot
        failed_when: never
      when: reboot_required_file.stat.exists or yum_update_result.changed_packages # Reboot if file exists or packages were updated
