---
- name: Install Apache and PostgreSQL
  hosts: all
  become: true  # This allows the tasks to run with sudo privileges
  tasks:
    - name: Update apt cache
      ansible.builtin.dnf:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Apache2 package
      ansible.builtin.dnf:
        name: apache2
        state: present

    - name: Ensure Apache2 service is running and enabled
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Install PostgreSQL package
      ansible.builtin.apt:
        name: postgresql
        state: present

    - name: Ensure PostgreSQL service is running and enabled
      ansible.builtin.service:
        name: postgresql
        state: started
        enabled: true
