---
- name: Restore the vm from a snapshot
  hosts: all
  gather_facts: false
  vars: # You provide values for these variables from a survey in the job template
    vm_name:
    ns:
    vm_snapshot_name:

  tasks:

    - name: Obtain the details about the VirtualMachine Snapshot for vm1
      kubernetes.core.k8s_info:
        api_version: snapshot.kubevirt.io/v1alpha1
        kind: VirtualMachineSnapshot
        namespace: "{{ ns }}"
        name: "{{ vm_snapshot_name }}"
      register: vm_snapshot_details 1

    - name: Stop the Virtual Machine vm1 2
      redhat.openshift_virtualization.kubevirt_vm:
        name: "{{ vm_name }}"
        namespace: "{{ ns }}"
        running: false
        wait: true

    - name: Create Restore Object to restore the VM from the snapshot
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: snapshot.kubevirt.io/v1alpha1
          kind: VirtualMachineRestore 3
          metadata:
            generateName: "{{ vm_name }}-restore-" 4
            namespace: "{{ ns }}"
            ownerReferences:
              - apiVersion: kubevirt.io/v1
                blockOwnerDeletion: false
                kind: VirtualMachine
                name: "{{ vm_name }}"
                uid: "{{ vm_snapshot_details.​resources[0].​metadata.​ownerReferences[0].​uid }}" 5
          spec:
            target:
              apiGroup: kubevirt.io
              kind: VirtualMachine
              name: "{{ vm_name }}"
            virtualMachineSnapshotName: "{{ vm_snapshot_details.​resources[0].​metadata.​name }}" 6 7
        wait: true
        wait_timeout: 600
        wait_condition:
          type: Ready
